apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    run: hello
spec:
  ports:
    # the port that this service should serve on
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
      run: orders
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: hello
    spec:
      containers:
      - name: hello
        image: otomato/hello:0.1
        ports:
        - containerPort: 5000
  strategy:
    type: Recreate
minReadySeconds: 5
